language: rust
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdbus-1-dev
addons:
  apt:
    packages:
    - libdbus-1-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
